# Generated by Django 3.1.5 on 2021-03-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Weight', models.FloatField()),
                ('Height', models.FloatField()),
                ('Gender', models.CharField(max_length=10)),
                ('StartingDate', models.DateField()),
                ('EndingDate', models.DateField()),
                ('DueToDietFor', models.CharField(max_length=200)),
                ('Carbohydrates', models.FloatField()),
                ('Fats', models.FloatField()),
                ('Protin', models.FloatField()),
                ('AfterWakeUp', models.TextField()),
                ('BeforeBreakfast', models.TextField()),
                ('Breakfast', models.TextField()),
                ('Lunch', models.TextField()),
                ('Snacks', models.TextField()),
                ('Dinner', models.TextField()),
                ('MidNeightDrink', models.TextField()),
                ('Notes', models.TextField()),
                ('Excercise', models.TextField()),
            ],
        ),
    ]
