# Generated by Django 3.1.5 on 2021-03-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20210304_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
